/*
-- Query: select * from club
-- Date: 2022-04-27 23:45
*/
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Arsenal','Emirates Stadium','https://www.arsenal.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Aston Villa','Villa Park','https://www.avfc.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Barnsley','Oakwell',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Birmingham City','St. Andrew\'s Trillion Trophy Stadium',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Blackburn Rovers','Ewood Park',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Blackpool','Bloomfield Road',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Bolton Wanderers','University of Bolton Stadium',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Bournemouth','Vitality Stadium','http://www.afcb.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Bradford City','Valley Parade',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Brentford','Brentford Community Stadium','https://www.brentfordfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Brighton','Amex Stadium','https://www.brightonandhovealbion.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Burnley','Turf Moor','http://www.burnleyfootballclub.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Cardiff','Cardiff City Stadium','http://www.cardiffcityfc.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Charlton Athletic','The Valley',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Chelsea','Stamford Bridge','https://www.chelseafc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Coventry City','Highfield Road',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Crystal Palace','Selhurst Park','http://www.cpfc.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Derby County','Pride Park Stadium',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Everton','Goodison Park','http://www.evertonfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Fulham','Craven Cottage','http://www.fulhamfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Huddersfield','John Smith\'s Stadium','https://www.htafc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Hull City','KCOM Stadium','http://www.hullcitytigers.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Ipswich Town','Portman Road',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Lech Poznan',NULL,'https://www.lechpoznan.pl/');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Leeds','Elland Road','http://www.leedsunited.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Leicester','King Power Stadium','http://www.lcfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Liverpool','Anfield','http://www.liverpoolfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Man City','Etihad Stadium','http://www.mancity.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Man Utd','Old Trafford','http://www.manutd.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Middlesbrough','Riverside Stadium','http://www.mfc.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Newcastle','St. James\' Park','http://www.nufc.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Norwich','Carrow Road','http://www.canaries.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Nottingham Forest','City Ground',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Oldham Athletic','Boundary Park',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Portsmouth','Fratton Park',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Queens Park Rangers','Loftus Road',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Reading','Madejski Stadium',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Sheffield Utd','Bramall Lane','http://www.sufc.co.uk/?utm_source=www.premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Sheffield Wednesday','Hillsborough',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Southampton','St. Mary\'s Stadium','https://www.southamptonfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Spurs','Tottenham Hotspur Stadium','http://www.tottenhamhotspur.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Stoke City','bet365 Stadium','http://www.stokecityfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Sunderland','Stadium of Light','http://www.safc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Swansea City','Liberty Stadium','http://www.swanseacity.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Swindon Town','County Ground',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Watford','Vicarage Road','https://www.watfordfc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('West Brom','The Hawthorns','http://www.wba.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('West Ham','London Stadium','http://www.whufc.com/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Wigan Athletic','DW Stadium',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Wimbledon','Selhurst Park',NULL);
INSERT INTO `` (`Name`,`HomeStadium`,`Website`) VALUES ('Wolves','Molineux Stadium','http://www.wolves.co.uk/?utm_source=premier-league-website&utm_campaign=website&utm_medium=link');
